### Health Check

GET http://localhost:8080/api/health

###

POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "username": "Daniel",
  "email": "daniel@example.com",
  "password": "Titkos123!"
}

### Login - successful
# @name login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "Daniel",
  "password": "Titkos123!"
}

> {%
    client.global.set(
        "accessToken",
        response.body.accessToken
    );
%}

### Current authenticated user
GET http://localhost:8080/api/users/me
Authorization: Bearer {{accessToken}}

### Current user without token - expected 401
GET http://localhost:8080/api/users/me
